### ISSUE TITLE
(BUG) "The requested platform 'SmartThings-v2' was not registered by any plugin." 

### ISSUE THREAD

**Issue by vidgizmo** [tonesto7/homebridge-smartthings-v2#152]
## Verify the following before opening an trouble issue

**Go over all the following points, and put an `x` in all the boxes that apply.
If you're unsure about any of these, don't hesitate to ask. We're here to help!**

-  [x] That _OAuth_ is Enabled for the SmartApp under the IDE.
-  [?] The SmartApp and Device Handler are using the latest code available.
   The SmartApp shows appVersion 2.3.3 and appModified 04-28-2020 and branch master.
-  [?] That Both the SmartApps and Device Handlers have been _Published for You_ in the IDE.
   The SmartApp is published, but I do not have any Device Handlers installed. 
---
## About Your Setup
-  How many devices are detected?: None by the Homebridge app running on my Raspberry Pi, but 20 in the Homebridge-v2 SmartApp running on my iPhone.
-  Mobile App Version(Not required):
-  SmartApp Version: 2.3.3
-  Device Handler Version: N/A
-  Homebridge Version: maybe 1.1.0? 
  [5/22/2020, 11:24:56 AM] [HB Supervisor] Starting Homebridge with extra flags: -I -D
  [5/22/2020, 11:24:56 AM] [HB Supervisor] Started Homebridge v1.1.0 with PID: 3248
  [5/22/2020, 11:24:57 AM] Loaded config.json with 0 accessories and 2 platforms.
  [5/22/2020, 11:24:57 AM] ---
  [5/22/2020, 11:24:58 AM] Loaded plugin: homebridge-config-ui-x@4.20.0
  [5/22/2020, 11:24:58 AM] Registering platform 'homebridge-config-ui-x.config
-  NodeJS Version: 12.16.3

## Expected Behavior
Expecting Homebridge on my Raspberry Pi to start up and find devices.

## Current Behavior
Giving the following error messages at startup.
Error: The requested platform 'SmartThings-v2' was not registered by any plugin.

## Steps to Reproduce (for bugs)
Just boot the Raspberry Pi

## Context
Unable to get started with HomeBridge-v2 :(

## Config
here's the config file w/ redacted specific info
{
    "bridge": {
        "name": "Homebridge 696F",
        "username": "0E:90:41:DA:69:6F",
        "port": 51780,
        "pin": "860-18-426"
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "platform": "config"
        },
        {
            "platform": "SmartThings-v2",
            "name": "SmartThings-v2",
            "app_url": "https://graph-na02-useast1.api.smartthings.com:443/api/smartapps/installations/",
            "app_id": "a1a9d787-be4b-4e90-b708-da7083e293a2",
            "access_token": "96f21153-78b0-4e20-aa2f-************",
            "communityUserName": "tonesto7",
            "temperature_unit": "F",
            "validateTokenId": false,
            "logConfig": {
                "debug": true,
                "showChanges": true,
                "hideTimestamp": false,
                "hideNamePrefix": false,
                "file": {
                    "enabled": true
                }
            }
        }
    ]
}

Please include a copy of any relevant log output to assist in tracking down the bug
## Logs

[5/22/2020, 11:24:56 AM] [HB Supervisor] Starting Homebridge with extra flags: -I -D
[5/22/2020, 11:24:56 AM] [HB Supervisor] Started Homebridge v1.1.0 with PID: 3248
[5/22/2020, 11:24:57 AM] Loaded config.json with 0 accessories and 2 platforms.
[5/22/2020, 11:24:57 AM] ---
[5/22/2020, 11:24:58 AM] Loaded plugin: homebridge-config-ui-x@4.20.0
[5/22/2020, 11:24:58 AM] Registering platform 'homebridge-config-ui-x.config'
[5/22/2020, 11:24:58 AM] ---
[5/22/2020, 11:24:58 AM] Loading 2 platforms...
[5/22/2020, 11:24:58 AM] [Config] Initializing config platform...
[5/22/2020, 11:24:58 AM] [Config] Running in Service Mode
[5/22/2020, 11:24:58 AM] Error loading platform requested in your config.json at position 2
[5/22/2020, 11:24:59 AM] Error: The requested platform 'SmartThings-v2' was not registered by any plugin.
    at PluginManager.getPluginForPlatform (/usr/lib/node_modules/homebridge/src/pluginManager.ts:224:15)
    at /usr/lib/node_modules/homebridge/src/server.ts:386:37
    at Array.forEach (<anonymous>)
    at Server.loadPlatforms (/usr/lib/node_modules/homebridge/src/server.ts:373:27)
    at Server.start (/usr/lib/node_modules/homebridge/src/server.ts:152:29)
    at cli (/usr/lib/node_modules/homebridge/src/cli.ts:80:10)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:1133:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
    at Module.load (internal/modules/cjs/loader.js:977:32)
[5/22/2020, 11:24:59 AM] Got SIGTERM, shutting down Homebridge...
[5/22/2020, 11:25:04 AM] [HB Supervisor] Homebridge Process Ended. Code: 143, Signal: null
[5/22/2020, 11:25:09 AM] [HB Supervisor] Restarting Homebridge...

**Comment by bsaint9** [comment]
if it helps, I had the exact same issue.  I resolved it by reinstalling the plugin from the command line.  Once i did that, it finally booted up without that error.

**Comment by vidgizmo** [comment]
Thanks. I'll give that a try.
