### ISSUE TITLE
(BUG) 

### ISSUE THREAD

**Issue by blueharmony** [tonesto7/homebridge-smartthings-v2#46]
## Verify the following before opening an trouble issue
-  [X] That _OAuth_ is Enabled for the SmartApp under the IDE.
-  [X] The SmartApp and Device Handler are using the latest code available.
-  [X] That Both the SmartApps and Device Handlers have been _Published for You_ in the IDE.

---
## About Your Setup
-  How many devices are detected?: 2
-  Mobile App Version(Not required):
-  SmartApp Version: v2.1.0
-  Device Handler Version: v2.1.7
-  Homebridge Version: 0.4.50
-  NodeJS Version: v10.15.2

## Expected Behavior
The logaudit.json file should be opened or explain why not.

## Current Behavior
Homebridge cannot open the logaudit.json file. See log below.

## Steps to Reproduce (for bugs)
1. sudo systemctl start homebridge
2. tail -f daemon.log

## Context
Simply starting Homebridge and cleaning up any errors.

---
This error consistently shows in the daemon.log:

```
Jan  9 11:37:42 raspberrypi homebridge[2299]: [1/9/2020, 11:37:42 AM][SmartThings-v2]INFO: Fetching SmartThings-v2 Devices. NOTICE: This may take a moment if you have a large number of device data is being loaded!
Jan  9 11:37:42 raspberrypi homebridge[2299]: 2020-01-09T17:37:42.630Z '[FileStreamRotator] Failed to store log audit at:' 'logaudit.json' 'Error:' { Error: EACCES: **permission denied, open 'logaudit.json'**
Jan  9 11:37:42 raspberrypi homebridge[2299]:     at Object.openSync (fs.js:439:3)
Jan  9 11:37:42 raspberrypi homebridge[2299]:     at Object.writeFileSync (fs.js:1190:35)
Jan  9 11:37:42 raspberrypi homebridge[2299]:     at Object.FileStreamRotator.writeAuditLog (/usr/local/lib/node_modules/homebridge-smartthings-v2/node_modules/file-stream-rotator/FileStreamRotator.js:246:12)
Jan  9 11:37:42 raspberrypi homebridge[2299]:     at Object.FileStreamRotator.addLogToAudit (/usr/local/lib/node_modules/homebridge-smartthings-v2/node_modules/file-stream-rotator/FileStreamRotator.js:320:27)
Jan  9 11:37:42 raspberrypi homebridge[2299]:     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/homebridge-smartthings-v2/node_modules/file-stream-rotator/FileStreamRotator.js:437:36)
Jan  9 11:37:42 raspberrypi homebridge[2299]:     at EventEmitter.emit (events.js:194:15)
Jan  9 11:37:42 raspberrypi homebridge[2299]:     at /usr/local/lib/node_modules/homebridge-smartthings-v2/node_modules/file-stream-rotator/FileStreamRotator.js:483:20
Jan  9 11:37:42 raspberrypi homebridge[2299]:     at process._tickCallback (internal/process/next_tick.js:61:11)
Jan  9 11:37:42 raspberrypi homebridge[2299]:     at Function.Module.runMain (internal/modules/cjs/loader.js:745:11)
Jan  9 11:37:42 raspberrypi homebridge[2299]:     at startup (internal/bootstrap/node.js:283:19)
Jan  9 11:37:42 raspberrypi homebridge[2299]:   errno: -13,
Jan  9 11:37:42 raspberrypi homebridge[2299]:   syscall: 'open',
Jan  9 11:37:42 raspberrypi homebridge[2299]:   code: 'EACCES',
Jan  9 11:37:42 raspberrypi homebridge[2299]:   path: 'logaudit.json' }
Jan  9 11:37:42 raspberrypi homebridge[2299]: [1/9/2020, 11:37:42 AM] Homebridge is running on port 51826.

```

**Comment by tonesto7** [comment]
that means the location where the config.json is stored does not have access to that folder

**Comment by blueharmony** [comment]
I'm not sure I understand. Here is my config.json permissions data:

The config.json is located in /var/lib/homebridge/config.jar:
-rw-r--r-- 1 homebridge homebridge  1728 Jan  9 12:12 config.json

The homebridge directory is owned by homebridge:
drwxr-xr-x 4 homebridge homebridge 4096 Jan  9 12:00 homebridge

/var and /var/lib are owned by root.

What permissions should I be changing and how?

Contents of config.json:
```
{
    "bridge": {
        "name": "Homebridge",
        "username": "CB:22:3D:E2:CE:31",
        "port": 51826,
        "pin": "033-44-254"
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8080,
            "auth": "form",
            "theme": "auto",
            "restart": "sudo -n systemctl restart homebridge",
            "tempUnits": "f",
            "sudo": true,
            "debug": false,
            "log": {
                "method": "systemd"
            },
            "platform": "config"
        },
        {
            "refreshToken": "eyJhbGciOiJIUzUxMiIsImprdSI6Ii9vYXV0aC9pbnRlcm5hbC9qd2tzIiwia2lkIjoiZGVmYXVsdCIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE1Nzg1OTM1NTEsInJlZnJlc2hfY2lkIjoicmluZ19vZmZpY2lhbF9hbmRyb2lkIiwicmVmcmVzaF9zY29wZXMiOlsiY2xpZW50Il0sInJlZnJlc2hfdXNlcl9pZCI6Njk4NTE2NSwicm5kIjoiUzByVGRxLW9BU05nX3ciLCJ0eXBlIjoicmVmcmVzaC10b2tlbiJ9.8avdL30swfUwHWAMObvCaToB9pOyHuZxMiP1rV-8W7eb5lngHHXtv9c2EoS03NvbGkcayNX2sQBZyWQatUE3_g",
            "platform": "Ring"
        },
        {
            "platform": "SmartThings-v2",
            "name": "SmartThings-v2",
            "app_url": "https://graph.api.smartthings.com:443/api/smartapps/installations/",
            "app_id": "4b28aaa7-a364-452b-bf3a-7a67bb488053",
            "access_token": "27c2c090-6769-4bff-972f-9ce0d4532865",
            "temperature_unit": "F",
            "validateTokenId": false,
            "logConfig": {
                "debug": false,
                "showChanges": true,
                "hideTimestamp": false,
                "hideNamePrefix": false,
                "file": {
                    "enabled": true
                }
            }
        }
    ]
}
```

**Comment by blueharmony** [comment]
I just upgraded to 2.1.12 and no longer see this error! Thank. :-)
